# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sealedsecrets < Formula
  desc ""
  homepage "https://github.com/hfoxy/sealedsecrets"
  version "0.0.2"

  on_macos do
    url "https://github.com/hfoxy/sealedsecrets/releases/download/v0.0.2/sealedsecrets_0.0.2_darwin_all.tar.gz"
    sha256 "8b3bbe809ef62950f80505ba16cfb1f547746ff7762e7ca5245dfb7a65a447f8"

    def install
      bin.install "sealedsecrets"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hfoxy/sealedsecrets/releases/download/v0.0.2/sealedsecrets_0.0.2_linux_arm64.tar.gz"
      sha256 "21571e6c7330678c62c54ec2ddfdb78621d744aa4e6d2f10c659ac4394e6f4f3"

      def install
        bin.install "sealedsecrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hfoxy/sealedsecrets/releases/download/v0.0.2/sealedsecrets_0.0.2_linux_amd64.tar.gz"
      sha256 "dddd37507aabceddb467c7fad0b73c7fb1d72b1536835a72abb621bbb48984a0"

      def install
        bin.install "sealedsecrets"
      end
    end
  end
end
